### ISSUE TITLE
Variant of selection Article not change to related image

### ISSUE THREAD

**Issue by Cyber-Devs** [aimeos/aimeos-laravel#445]
1. Version (e.g. de-master, laravel )
2. Operating system (Linux, Mac, Windows)

**Variant Article not change to related image**
variants of the selection article on selecting change the price(rebate) as well the stock level but not the variant image in product details page.

**Comment by aimeos** [comment]
Did it work before in your setup?

**Comment by aimeos** [comment]
Has been fixed now. The problem was a combination of backend and frontend and you need to save your variant articles after the update again so the variant attributes are correctly attached to the images.

**Comment by Cyber-Devs** [comment]
supper has been solved.

**Comment by Cyber-Devs** [comment]
After update fixed details action but arise the same issue again.varaint of selection Artikel not changing to related img.

**Comment by aimeos** [comment]
Please try `aimeos/ai-client-html:2022.04.x-dev`

**Comment by Cyber-Devs** [comment]
still the same responce, 2022.04.x-dev, dev-master as well rebuild the index but no clue..

**Comment by aimeos** [comment]
Fixed in dev-master and 2022.04

**Comment by Cyber-Devs** [comment]
has been solved in Variante as well in slider action but still no response in product list view...

**Comment by aimeos** [comment]
In the product list view it's not implemented to show the variant image, there's only a hover transition between the first and second image (if available).
